### PR TITLE
Fix support to MongoDB 4.x, 5.0 and 6.0

### LINKED ISSUE #34: MongoDB 6.0 contains breaking changes that make the setup action fail
Following the deprecation warning:

>> Warning: the "mongo" shell has been superseded by "mongosh",
which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in

the latest MongoDB i.e. `6.0` does not support `mongo` as the command line tool which results in the following container startup error:

>> OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "mongo": executable file not found in $PATH: unknown

This affects all users who do not specify a concrete MongoDB version, as `latest` is the default version for the `mongodb-version` parameter.

//cc: @danielmarbach

### PR DESCRIPTION
**Pull request by ecarruda**
Closes #34

### CODE REVIEW

**Comment by marcuspoehls** [comment]
@ecarruda Hey Evandro, thank you for the merge request! I really appreciate your work. The tests are failing for MongoDB 4.x because the tests try to use `mongosh` instead of `mongo`. I can’t see the issue right now. Do you have an idea?

File: start-mongodb.sh [hunk 1]
```diff
@@ -47,7 +52,7 @@ echo "::group::Waiting for MongoDB to accept connections"
 sleep 1
 TIMER=0
 
-until docker exec --tty mongodb mongosh --port $MONGODB_PORT --eval "db.serverStatus()" # &> /dev/null
+until docker exec --tty mongodb $MONGO_CLIENT --port $MONGODB_PORT --eval "db.serverStatus()" # &> /dev/null
```
Comment (idorrington92) [inline start-mongodb.sh:55]:
```suggestion
until docker exec --tty mongodb mongosh --port $MONGODB_PORT --eval "db.serverStatus()" # &> /dev/null
```
For mongoDB v4 this changes mongosh to mongo. Is that right? It might be why the tests are failing

Comment (marcuspoehls) [reply start-mongodb.sh:55]: Hey Iain, MongoDB 4.x comes with a `mongo` command. Since MongoDB 5.x, there’s the newer `mongosh` command. The `$MONGO_CLIENT` variable should resolve the correct command depending on the defined MongoDB version.

Comment (ecarruda) [reply start-mongodb.sh:55]: Let me check what happened with the Actions scripts, because locally everything worked, give me some time, probably some mess with shell environment vs my wildcard here:

```
if [[ $MONGODB_VERSION == 4* ]]; then
   MONGO_CLIENT="mongo"
 else
   MONGO_CLIENT="mongosh --quiet"
 fi
```

Working on it...

**Comment by ecarruda** [comment]
Fixed wildcard problem sh vs bash, it worked locally on my MacOS even using and i didn't realize that I was using a bash wildcard without bash, sorry for the mess, fixed using shell script built in way. Waiting my local tests but I did some tests on linux and test workflow and all good. :)

**Comment by marcuspoehls** [comment]
Awesome! Thank you for the refinements! 👍

**Comment by ecarruda** [comment]
> Awesome! Thank you for the refinements! 👍

Thank you guys for the opportunity to help on this amazing actions solution to MongoDB in Github

**Comment by ecarruda** [comment]
@marcuspoehls now all is good, just requested your review again and I also appreciate @idorrington92 review too :) Thank you guys. If you need some change or dislike the approach let me know.

**Comment by idorrington92** [comment]
That was a subtle bug! Thanks for fixing this so quickly @ecarruda

File: start-mongodb.sh [hunk 2]
```diff
@@ -18,6 +18,17 @@ if [ -z "$MONGODB_VERSION" ]; then
 fi
 
 
+echo "::group::Selecting correct MongoDB client"
+if [ "`echo $MONGODB_VERSION | cut -c1-1`" = "4" ]; then
```
Comment (marcuspoehls) [inline start-mongodb.sh:22]: @ecarruda Do you know if we can just use `1` instead of `1-1` for the first character?

```suggestion
if [ "`echo $MONGODB_VERSION | cut -c 1`" = "4" ]; then
```

Otherwise, I think a space between `-c` and `1-1` would be nice to increase readability. Well, hopefully my requested space doesn’t break anything.

**Comment by marcuspoehls** [comment]
@ecarruda Just left a minor comment. Looks good overall. I’m happy to merge it. Will just wait in case you have an opinion related to my comment :)

File: start-mongodb.sh (hunk 2 above)
Comment (ecarruda) [reply start-mongodb.sh:22]: Let me do some tests here

Comment (ecarruda) [reply start-mongodb.sh]: You are right @marcuspoehls thanks for this tip, checked on cut man page about this syntax and using -c alone (without --complement) we can improve this syntax as you suggested, changed it :)

**Comment by ecarruda** [comment]
> @ecarruda Just left a minor comment. Looks good overall. I’m happy to merge it. Will just wait in case you have an opinion related to my comment :)

Yes, thanks. I'm always accept syntax improvements suggestion, I checked on cut man pages definitions and tested it here before and all good. Sent the change :) Thank you! Requested you review again

**Comment by marcuspoehls** [comment]
@ecarruda Great 😃 I’ll merge this PR as soon as the test pipeline finishes

**Comment by ecarruda** [comment]
> @ecarruda Great 😃 I’ll merge this PR as soon as the test pipeline finishes

Pretty good!!! Let me ask you, do you have any ideia/roadmap about when you will have another release with this change?

**Comment by marcuspoehls** [comment]
New release comes in 10 minutes

**Comment by marcuspoehls** [comment]
I’ve published version `1.8.0` to the GitHub Marketplace

**Comment by ecarruda** [comment]
> I’ve published version `1.8.0` to the GitHub Marketplace

Thank you starting to update my workflows here to test it :)

**Comment by marcuspoehls** [comment]
Cool! Please let me know how it works :)

**Comment by ecarruda** [comment]
> I’ve published version `1.8.0` to the GitHub Marketplace

Just one thing strange, before i was using as your documentation but for some reason market is saying to use with `v` prefix now

```
- name: MongoDB in GitHub Actions
  uses: supercharge/mongodb-github-action@v1.8.0
```

**Comment by ecarruda** [comment]
All working good here @marcuspoehls just this problem with the version tag, just let me know if you are going to do any change to rollback to `1.8.0` instead of `v1.8.0` then I decide my move here, if you are going to let with the `v` prefix some update on market documentation is also needed.

**Comment by marcuspoehls** [comment]
@ecarruda Thank you for pointing this out! I’ve deleted the tag with the `v` prefix. And tagged a new version (including release) using just `1.8.0`.
